package com.stocker.api.domain.entity;

public enum Category {
    GENERAL_MERCHANDISE,
    CONSUMER_GOODS,
    DURABLE_GOODS,
    NON_DURABLE_GOODS,
    PERISHABLES,
    NON_PERISHABLES,
    LUXURY_ITEMS,
    ESSENTIALS,
    ELECTRONICS_AND_APPLIANCES,
    FURNITURE_AND_HOME_DECOR,
    CLOTHING_AND_ACCESSORIES,
    TOYS_AND_GAMES,
    BEAUTY_AND_HEALTH,
    SPORTS_AND_OUTDOORS,
    AUTOMOTIVE_AND_TOOLS,
    OFFICE_AND_SCHOOL_SUPPLIES,
    PET_CARE,
    FOOD_AND_BEVERAGES,
    ENTERTAINMENT,
    OTHER
}

